- name: "Install Anki"
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: "Create temporary dir"
      file:
        path: /tmp/anki/
        state: directory

    - name: "Download Anki"
      get_url:
        url: "https://github.com/ankitects/anki/releases/download/2.1.61/anki-2.1.61-linux-qt6.tar.zst"
        dest: "/tmp/anki/anki.tar.zst"

    - name: "Uncompress Anki"
      unarchive:
        src: "/tmp/anki/anki.tar.zst"
        dest: "/tmp/anki/"

    - name: "Install Anki"
      command:
        chdir: "/tmp/anki/anki-2.1.61-linux-qt6/"
        cmd: "./install.sh"
