- name: "Install latest discord for Debian"
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: "Install Packages"
      register: aptout
      apt:
        state: latest
        deb: https://discord.com/api/download?platform=linux&format=deb

    - debug: var=aptout
