- name: "Install personal pip3 packages"
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: "Install Packages"
      register: pipout
      pip:
        state: latest
        name: 
          - yt-dlp
          - black
          - trash-cli


    - debug: var=pipout.stdout
