- name: "Install personal pip3 packages"
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: "Install Packages"
      register: pipout
      pip:
        state: latest
        name: 
          - bs4
          - requests
          - PyYAML
          - python3-venv

    - debug: var=pipout.stdout
