- name: "Programming packages for Debian"
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: "Install Packages"
      register: aptout
      apt:
        state: latest
        name: 
          - g++
          - cmake
          - gcc
          - python3
          - python3-pip
          - tree
          - git
          - g++
          - zip
          - gzip
          - zstd 
          - net-tools
          - npm
          - gdb
          - nodejs
          - dos2unix
          - pkg-config
          - build-essential
          - checkinstall
          - curl
          - wget
          - gnupg
          - lsb-release
          - ffmpeg

    - debug: var=aptout
