- name: "Install Syncthing for Debian"
  hosts: localhost
  connection: local
  tasks:
    - name: "Download PGP keys"
      register: downout
      ansible.builtin.get_url:
        url: "https://syncthing.net/release-key.gpg"
        dest: "/usr/share/keyrings/syncthing-archive-keyring.gpg"

    - debug: var=downout


    - name: "Update apt sources"
      register: cmdout
      shell:
        cmd: echo "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list
    - debug: var=cmdout


    - name: "Install Syncthing"
      register: aptout
      apt:
        update-cache: true
        state: latest
        name: 
          - syncthing
    - debug: var=aptout

